[package]
name = "bombus-slint"
version = "0.1.0"
authors = ["mmcmains <mmcmains@gsandf.com>"]
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
slint = "1.0"
souvlaki = "0.7.0"

[build-dependencies]
slint-build = "1.0"
