import { Grid, Album, Theme } from "./global.slint";

export component AlbumLayout inherits VerticalLayout {
    in property <int> selected-index;
    in property <int> items-per-row;
    in property <length> offset-x;
    in property <Album> album;
    HorizontalLayout {
        x: mod(selected-index, items-per-row) * Grid.outer-width + offset-x;
        height: 24px;
        width: Grid.outer-width;
        // Make a triangle
        Path {
            width: 100%;
            height: 24px;
            fill: Theme.system-grey-5;
            MoveTo {
                x: 0;
                y: 24;
            }

            LineTo {
                x: 16;
                y: 0;
            }

            LineTo {
                x: 32;
                y: 24;
            }

            Close { }
        }

        animate x {
            duration: 250ms;
            easing: ease-in-out;
        }
    }

    HorizontalLayout {
        Rectangle {
            width: offset-x * 2;
        }
        Rectangle {
            background: Theme.system-grey-5;
        }
        Rectangle {
            width: offset-x * 2;
        }
    }

}
