import { ScrollView } from "std-widgets.slint";
import { Grid, Logic, Const } from "global.slint";
import { Cover } from "cover.slint";

export { Logic }

export component AppWindow inherits Window {
    in property <[color]> albums;
    in property <int> selected-index;
    min-width: Grid.outer-width;
    min-height: Grid.outer-height;

    ScrollView {
        property <int> items_per_row: Math.floor(parent.width / Grid.outer-width);
        property <int> rows: Math.ceil(albums.length / items-per-row);
        // caculate the remaining width so we can manually center the items
        property <length> offset-x: (parent.width - (Grid.outer-width * items-per-row)) / 2;
        property <length> selected-y: Math.floor(selected-index / items-per-row) * Grid.outer-height;

        height: parent.height;
        width: parent.width;
        viewport-height: Grid.outer-height * rows + (selected-index == Const.i32-max ? 0 : Grid.outer-height);

        HorizontalLayout {
            y: Math.floor(selected-index / items-per-row) * Grid.outer-height + Grid.outer-height;
            height: selected-index == Const.i32-max ? 0 : Grid.outer-height;
            Rectangle {
                background: black;
            }
        }

        // loop over albums creating the grid
        for album [index] in albums: Rectangle {
            property <length> pos-y: Math.floor(index / items-per-row) * Grid.outer-height;
            x: mod(index, items-per-row) * Grid.outer-width + offset-x;
            y: pos-y > selected-y ? pos-y + Grid.outer-height : pos-y;
            height: Grid.outer-height;
            width: Grid.outer-width;
            cover := Cover {
                bg-color: albums[index];
                index: index;
            }
        }
    }
}
