export global Grid {
    in-out property <length> inner-size: 264px;
    in-out property <length> spacing: 16px;
    in-out property <length> outer-height: inner-size + spacing * 2;
    in-out property <length> outer-width: inner-size + spacing * 2;
}

export global Logic {
    pure callback album-clicked(int);
}

export global Const {
    out property <int> i32-max: 2147483647;
}

export struct Track {
    duration: string,
    name: string,
    number: int,
}

export struct Album {
    artist: string,
    title: string,
    tracks: [Track],
    image: image
}
