export struct Track {
    length: string,
    title: string,
    number: int,
    uri: string
}

export struct Album {
    id: string,
    artist: string,
    title: string,
    tracks: [Track],
    image: image
}

export struct Library {
    name: string,
    ip: string,
    color: color
}

export struct Color {
    label_quaternary: color,
    label_secondary: color,
    label_tertiary: color,
    label: color,
    link: color,
    placeholder_text: color,
    separator: color,
    system_blue: color,
    system_brown: color,
    system_fill_quaternary: color,
    system_fill_secondary: color,
    system_fill_tertiary: color,
    system_fill: color,
    system_white: color,
    system_black: color,
    system_gray: color,
    system_green: color,
    system_indigo: color,
    system_orange: color,
    system_pink: color,
    system_purple: color,
    system_red: color,
    system_teal: color,
    system_yellow: color,
    under_page_background: color,
    window_background: color,
}

export global Theme {
    in-out property <Color> color;
}

export global Grid {
    in-out property <length> inner-size: 264px;
    in-out property <length> spacing: 24px;
    in-out property <length> outer-height: inner-size + spacing * 2 + spacing;
    in-out property <length> outer-width: inner-size + spacing * 2;
}

export global Logic {
    in-out property <string> now-playing-track;
    in-out property <string> now-playing-album;
    pure callback album-clicked(int);
    pure callback track-clicked(Track);
    pure callback add-library(string, string, color);
    pure callback load-library(Library);
    pure callback remove-library(Library);
    pure callback play-album(Album);
}

export global Const {
    out property <int> i32-max: 2147483647;
}
