import { Library, Theme } from "global.slint";
import { BodySmall, Title3, Headline } from "typography.slint";
import { TrackLayout } from "tracklayout.slint";

export component LibraryItem inherits Rectangle {
    in property <Library> library;
    background: touch.has-hover ? Theme.color.system-fill-secondary : transparent;

    HorizontalLayout {
        padding: 8px;
        spacing: 8px;

        VerticalLayout {
            alignment: center;
            padding-left: 8px;
            padding-right: 4px;

            Rectangle {
                height: 16px;
                width: self.height;
                border-radius: self.height;
                background: library.color;
            }
        }

        VerticalLayout {
            spacing: 4px;
            BodySmall {
                text: library.ip;
            }

            Title3 {
                text: library.name;
            }
        }
    }

    touch := TouchArea {
        mouse-cursor: pointer;
    }
}
