import { Track, Theme, Logic } from "global.slint";
import { Body, BodySmallMono } from "typography.slint";

export component TrackLayout inherits Rectangle {
    in property <Track> track;
    property <length> left-right-padding: 8px;
    border-color: Theme.system-grey-5;
    border-width: 2px;
    background: touch.has-hover ? Theme.color.system-blue : Theme.color.system-fill-tertiary;

    HorizontalLayout {
        padding-left: left-right-padding;
        padding-right: left-right-padding;
        alignment: space-between;

        HorizontalLayout {
            HorizontalLayout {
                spacing: 6px;
                padding-right: 10px;

                BodySmallMono {
                    opacity: 0.75;
                    vertical-alignment: center;
                    horizontal-alignment: center;
                    text: track.number;
                    width: 18px;
                    font-family: "'SF Mono', SFMono-Regular, ui-monospace, monospace";
                }

                Rectangle {
                    y: 6px;
                    height: parent.height - 12px;
                    width: 2px;
                    background: Theme.color.separator;
                }
            }

            Body {
                vertical-alignment: center;
                horizontal-alignment: left;
                text: track.name;
            }
        }

        BodySmallMono {
            opacity: 0.75;
            vertical-alignment: center;
            horizontal-alignment: left;
            text: track.duration;
            font-family: "'SF Mono', SFMono-Regular, ui-monospace, monospace";
        }
    }

    touch := TouchArea {
        mouse-cursor: pointer;
        clicked => {
            Logic.track-clicked(track);
        }
    }
}
