import { Track, Theme, Logic } from "global.slint";
import { Body, BodySmallMono } from "typography.slint";

export component TrackLayout inherits Rectangle {
    in property <Track> track;
    property <length> left-right-padding: 8px;
    background: touch.has-hover ? Theme.color.system-blue : Theme.color.system-fill-tertiary;
    border-radius: 8px;

    HorizontalLayout {
        padding-left: left-right-padding;
        padding-right: left-right-padding;
        alignment: space-between;

        HorizontalLayout {
            HorizontalLayout {
                spacing: 6px;
                padding-right: 10px;

                BodySmallMono {
                    opacity: 0.75;
                    vertical-alignment: center;
                    horizontal-alignment: center;
                    text: track.number;
                    width: 18px;
                }

                Rectangle {
                    y: 6px;
                    height: parent.height - 12px;
                    width: 2px;
                    background: Logic.now-playing-track == track.uri ? Theme.color.system-blue : Theme.color.separator;
                    border-radius: 2px;
                }
            }

            Body {
                vertical-alignment: center;
                horizontal-alignment: left;
                overflow: elide;
                text: track.title;
            }
        }

        HorizontalLayout {
            padding-left: 8px;

            BodySmallMono {
                opacity: 0.75;
                vertical-alignment: center;
                horizontal-alignment: left;
                text: track.length;
            }
        }
    }

    touch := TouchArea {
        mouse-cursor: pointer;
        clicked => {
            Logic.track-clicked(track);
        }
    }
}
