// https://developer.apple.com/design/human-interface-guidelines/typography#macOS-built-in-text-styles

export component LargeTitle inherits Text {
    font-size: 26px;
    horizontal-alignment: left;
}

export component Headline inherits Text {
    opacity: 0.75;
    font-size: 13px;
    font-weight: 100;
    horizontal-alignment: left;
}

export component Body inherits Text {
    font-size: 13px;
    font-weight: 500;
    horizontal-alignment: left;
}
